### ISSUE TITLE
Use of private label in hashmap.h line 16

### ISSUE THREAD

**Issue by thomas-vaiarella** [TomPeng19971208/CS4500_A1_Part2#5]
Per the CwC spec, _private:_ is not a valid access modifier

**Comment by BlueSpud** [comment]
Also the private fields are implantation details and should just be removed entirely

**Comment by TomPeng19971208** [comment]
It should be fixed by now. Don't hesitate to contact me if you have any questions, I will be checking github on a regular basis and respond ASAP. If you still have questions, you can email me at peng.zi@husky..., i'd be happy to address your concern. I will change test spec all at once, as for now, teams are still trying to reach an agreement on what methods should be in the interface. 

Just to clarify, Map interface allows all kinds of implementation (Hashmap, TreeMap, Linked....). I am sry that I didn't catch it in the first place when my partner submitted it. I renamed the file to map.h
